name: Test All #name of workflow
on: [push] #trigger

jobs:
    deploy:
       runs-on: ubuntu-latest #configues job to run on latest version of ubuntu, github creates a virtual machine
       strategy:
         fail-fast: false
         matrix:
            python-version: [3.8]
       steps: #just something you need to do, checks repository against runner allowing you to run script
        - uses: actions/checkout@master

        - name: Initialize Python 3.8
          uses: actions/setup-python@v1 #sets up python
          with:
            python-version: ${{matrix.python-version}}

        - name: Create and start virtual environment
          run: | #execute command
            python3 -m venv venv
            source venv/bin/activate

        - name: Install dependencies
          run: |
            python3 -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Run app
          run: |
            python3 test_app.py

        - name: Test hello world
          run: |
            python hello_world.py

        - name: Cat
          run: |
            cat soonway.txt
